✨ Add Typing practice html structure
Koch-Dustin/TypingPractice pull request #2
Opened 2022-11-07 12:12 UTC by Koch-Dustin

Changes:
   - Add HTML & Css Structure

PR: #1

2022-11-07 13:52 UTC, DevBastiS requested changes
A lot of work to do here.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +    <div class="wrapper" id="game">
wrapper is not a good name for a class.
Please stick to the BEM notation.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +      <div class="content-box">
content-box is also not a good name.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <input type="number" placeholder="Generated Words" id="word_count" max="25" onKeyDown="return false">
```suggestion
        <input type="number" placeholder="Generated Words" id="word-count" max="25" onKeyDown="return false">
```

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <input type="number" placeholder="Generated Words" id="word_count" max="25" onKeyDown="return false">
Why is there a max?

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <button onclick="generateWords()" >Generate</button>
```suggestion
        <button onclick="generateWords()">Generate</button>
```

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <p id="paragraph"></p>
paragraph is not really a speaking id name for this.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <div class="content">
Replace "content" with a speaking name. "results" might be fine.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <div class="best-score-container">
```suggestion
        <div class="best-score">
```

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +    <div class="wrapper" id="scoreboard">
"wrapper" -> see above.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +      <div class="content-box">
content-box -> see above.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <div class="best-score-container">
What does "best-score-container" mean?

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <div id="left">Mistakes <span id="today_mistakes">0</span></div>
```suggestion
          <div id="left">Mistakes <span id="today-mistakes">0</span></div>
```

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <div id="right">CPM: <span id="today_cpm">0</span></div>
```suggestion
          <div id="right">CPM: <span id="today-cpm">0</span></div>
```

Also ids have to be unique.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <div id="left">Mistakes <span id="today_mistakes">0</span></div>
"left" id is not unique

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <div id="left">Mistakes: <span id="last_mistakes">0</span></div>
left id is not unique

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +          <div id="right">CPM: <span id="last_cpm">0</span></div>
right id is not unique.

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +        <p>The best score gets selected by the highest CPM</p>
What does cpm mean?

2022-11-07 13:52 UTC, DevBastiS commented on index.html
> +    <script src="../js/script.js"></script>
script doesn't exist yet.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
```suggestion
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
This is not allowed anyway since DSGVO and stuff :D But it is ok for this training.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.wrapper .input-field{
Give this wrapper a speaking name and then use BEM to select the input field below.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.wrapper .input-field{
```suggestion
.wrapper .input-field {
```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.wrapper .content-box{
BEM here as well.
```suggestion
.wrapper .content-box {
```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.content-box .typing-text{
```suggestion
.content-box .typing-text {
```

Also BEM

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.typing-text::-webkit-scrollbar{
:: selectors shouldn't be needed for this task.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.typing-text::-webkit-scrollbar{
```suggestion
.typing-text::-webkit-scrollbar {
```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.typing-text p{
BEM

```suggestion
.typing-text p {
```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +.typing-text p span{
BEM

```suggestion
.typing-text p span {
```

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
```suggestion
}

```

Do this and add BEM Notation for all CSS Classes.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +@media (max-width: 745px) {
media queries shouldn't be needed for this task.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +@media (max-width: 518px) {
same here.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +#scoreboard {
Don't use # selectors for this task.

2022-11-07 13:52 UTC, DevBastiS commented on style.css
> +}
Missing EOF.

2022-11-07 14:55 UTC, Koch-Dustin commented on index.html
> +        <input type="number" placeholder="Generated Words" id="word_count" max="25" onKeyDown="return false">
Because it would take so much space that you couldn't see all of the Text but i maxed it out at 40 now. There it is the perfect size so it would just not go beneath the other content. and i Think 40 words should be enough to write.

2022-11-09 08:26 UTC, DevBastiS requested changes

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +        <div class="content">
Still open.

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +      <div class="typing-practice-game-div">
"div" is not a good name. 
Think about it like a variable. You wouldn't name your variable "Something...Variable".

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +    <div class="design-of-game-boxes" class="scoreboard" id="scoreboard">
```suggestion
    <div class="scoreboard" id="scoreboard">
```

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +        <div class="best-score-container">
Still open

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +        <div class="best-score-container">
Still open

2022-11-09 08:26 UTC, DevBastiS commented on index.html
> +        <p>The best score gets selected by the highest CPM</p>
Still open

2022-11-14 07:21 UTC, DevBastiS requested changes

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +    <div class="design-of-game-boxes" class="scoreboard" id="scoreboard">
still open

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +        <div class="best-score">
```suggestion
        <div class="overall-best-score">
```

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +        <div class="best-score">
```suggestion
        <div class="todays-best-score">
```

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +        <div class="best-score">
```suggestion
        <div class="last-play-score">
```

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +        <p>The best score gets selected by the highest CPM</p>
still open

2022-11-14 07:21 UTC, DevBastiS commented on index.html
> +    <div class="design-of-game-boxes" id="game">
```suggestion
    <div class="game-box" id="game">
```

2022-11-15 09:54 UTC, DevBastiS requested changes

2022-11-15 09:54 UTC, DevBastiS commented on index.html
> +      <input type="text" class="input-field" />
```suggestion
      <input type="text" class="typing-input-field" />
```

2022-11-15 09:54 UTC, DevBastiS commented on index.html
> +          <div class="left">Mistakes: <span id="alltime_mistakes">0</span></div>
Classes like "left" and "right" are not good class names.
Stick to BEM Notation here as well.
```suggestion
          <div class="alltime-mistakes">Mistakes: <span id="alltime_mistakes">0</span></div>
```

2022-11-15 11:55 UTC, Koch-Dustin commented on index.html
> +          <div class="left">Mistakes: <span id="alltime_mistakes">0</span></div>
Those two class names where from testing, they aren't needed anymore. I removed them

2022-11-16 07:35 UTC, DevBastiS approved these changes

2022-11-16 07:35 UTC, DevBastiS commented on index.html
> +      <input type="text" class="input-field" />
This is still open.

2022-11-18 07:19 UTC, Nicojele approved these changes
Locks fine resolve opened Changes

2022-11-22 11:51 UTC, merged